# Generated by Django 3.0.2 on 2020-03-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/events/')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('ticket_price', models.FloatField(default=0.0, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('organisers', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
