# Generated by Django 3.0.2 on 2020-03-13 16:11

from django.utils.text import slugify
from django.db import migrations, models

from events.models import create_unique_slug


def add_slug_data(apps, schema_editor):
    Event = apps.get_model('events', 'Event')
    query = Event.objects.all()

    for event in query:
        event.slug = create_unique_slug(Event, event)
        event.save()


def remove_slug_data(apps, schema_editor):
    Event = apps.get_model('events', 'Event')
    Event.objects.update(slug='')


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_added_event_image_upload_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField()
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(
                max_length=100,
                default=''
            )
        ),
        migrations.RunPython(
            add_slug_data,
            remove_slug_data
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(
                max_length=100,
                unique=True
            )
        )
    ]
