# Generated by Django 3.0.2 on 2020-03-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('code', models.CharField(max_length=6, unique=True)),
                ('category', models.CharField(choices=[('1', 'Geology'), ('2', 'Geophysics'), ('3', 'Others')], max_length=2)),
                ('units', models.PositiveIntegerField(null=True)),
                ('description', models.TextField(blank=True)),
                ('curriculum', models.TextField(blank=True)),
                ('drive_link', models.URLField(blank=True)),
                ('prerequisites', models.TextField(blank=True)),
                ('lecturers', models.ManyToManyField(related_name='courses', to='people.Lecturer')),
            ],
        ),
    ]
