# Generated by Django 3.0.2 on 2020-01-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='drive_link',
            field=models.URLField(blank=True),
        ),
    ]
