# Generated by Django 3.0.2 on 2020-01-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_remove_lecturer_course'),
        ('courses', '0002_auto_20200118_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lecturers',
            field=models.ManyToManyField(related_name='courses', to='people.Lecturer'),
        ),
    ]
