# Generated by Django 3.0.2 on 2020-03-25 14:55

import os
import csv

from django.db import migrations, models


COURSE_DATA_PATH = os.path.join(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__)
)), 'course_data', 'curriculum')

CSV_FILES = [
    'geology.csv',
    'geophysics.csv',
    'others.csv',
]


def add_curriculum_and_prerequisites(apps, schema_editor):
    Course = apps.get_model('courses', 'Course')

    for file_ in CSV_FILES:
        with open(os.path.join(COURSE_DATA_PATH, file_)) as csv_file:
            csv_reader = csv.reader(csv_file)
            for row in csv_reader:
                code, curriculum, _, prerequisites = row
                course = Course.objects.get(code=code)
                course.curriculum = curriculum
                course.prerequisites = prerequisites
                course.save()


def remove_curriculum_and_prerequisites(apps, schema_editor):
    Course = apps.get_model('courses', 'Course')

    for file_ in CSV_FILES:
        with open(os.path.join(COURSE_DATA_PATH, file_)) as csv_file:
            csv_reader = csv.reader(csv_file)
            for row in csv_reader:
                code, _, _, _ = row
                course = Course.objects.get(code=code)
                course.curriculum = ''
                course.prerequisites = ''
                course.save()


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_drive_links'),
    ]

    operations = [
        migrations.RunPython(
            add_curriculum_and_prerequisites,
            remove_curriculum_and_prerequisites
        ),
    ]
