# Generated by Django 3.0.2 on 2020-01-25 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_data_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('1', 'Geology'), ('2', 'Geophysics'), ('3', 'Others')], max_length=2),
        ),
    ]
