# Generated by Django 3.0.2 on 2020-01-18 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturer',
            old_name='courses',
            new_name='course',
        ),
    ]
