# Generated by Django 3.0.2 on 2020-03-25 14:58

import csv
import os

from django.core.files import File
from django.db import migrations


EXCO_DATA_PATH = os.path.join(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__)
)), 'exco_data')

EXCO_IMAGE_PATH = os.path.join(EXCO_DATA_PATH, 'exco_images')


def add_exco_data(apps, schema_editor):
    Executive = apps.get_model('people', 'Executive')

    with open(os.path.join(EXCO_DATA_PATH, 'excos.csv')) as csv_file:
        csv_reader = csv.reader(csv_file)
        for row in csv_reader:
            name, position, twitter, ig, sc, image = row

            name_list = name.split(' ')
            firstname, lastname = ' '.join(name_list[:-1]), name_list[-1]
            exco = Executive.objects.create(
                first_name=firstname,
                last_name=lastname,
                position=position,
                twitter=twitter,
                instagram=ig,
                snapchat=sc,
            )
            if image:
                exco.image.save(image, File(open(os.path.join(
                    EXCO_IMAGE_PATH, image
                ), 'rb')))


def remove_exco_data(apps, schema_editor):
    Executive = apps.get_model('people', 'Executive')

    with open(os.path.join(EXCO_DATA_PATH, 'excos.csv')) as csv_file:
        csv_reader = csv.reader(csv_file)
        for row in csv_reader:
            name, position, twitter, ig, sc, image = row

            name_list = name.split(' ')
            firstname, lastname = ' '.join(name_list[:-1]), name_list[-1]
            Executive.objects.get(
                first_name=firstname,
                last_name=lastname,
                position=position,
                twitter=twitter,
                instagram=ig,
                snapchat=sc,
            ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            add_exco_data,
            remove_exco_data
        )
    ]
