# Generated by Django 3.0.2 on 2020-01-25 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_added_social_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='executive',
            name='snapchat',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
