# Generated by Django 3.0.2 on 2020-01-25 23:07
import csv
import os

from django.db import migrations


EXCO_DATA_PATH = os.path.join(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__)
)), 'exco_data')


def add_exco_data(apps, schema_editor):
    Executive = apps.get_model('people', 'Executive')

    with open(os.path.join(EXCO_DATA_PATH, 'excos.csv')) as csv_file:
        csv_reader = csv.reader(csv_file)
        for row in csv_reader:
            name, position, twitter, ig, sc, image = row

            name_list = name.split(' ')
            firstname, lastname = ' '.join(name_list[:-1]), name_list[-1]
            Executive.objects.create(
                first_name=firstname,
                last_name=lastname,
                position=position,
                twitter=twitter,
                instagram=ig,
                snapchat=sc,
                image=image,
            )


def remove_exco_data(apps, schema_editor):
    Executive = apps.get_model('people', 'Executive')

    with open(os.path.join(EXCO_DATA_PATH, 'excos.csv')) as csv_file:
        csv_reader = csv.reader(csv_file)
        for row in csv_reader:
            name, position, twitter, ig, sc, image = row

            name_list = name.split(' ')
            firstname, lastname = ' '.join(name_list[:-1]), name_list[-1]
            Executive.objects.get(
                first_name=firstname,
                last_name=lastname,
                position=position,
                twitter=twitter,
                instagram=ig,
                snapchat=sc,
                image=image,
            ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_added_snapchat_field'),
    ]

    operations = [
        migrations.RunPython(
            add_exco_data,
            remove_exco_data
        )
    ]
