# Generated by Django 3.0.2 on 2020-02-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_exco_data_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executive',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/people/'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/people/'),
        ),
    ]
